# Generated by Django 5.2.6 on 2025-10-11 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_censorinfo_movie_censor_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_movies', to='movies.director'),
        ),
    ]
